[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
callback_interface = "F7HuoZhamk9hawJcwLv9q4XnZXJv3cJwAe4BNuyA4Uri"
ext_swap = "MSwapi3WhNKMUGm9YrxGhypgUEt7wYQH3ZgG32XoWzH"
m_ext = "3C865D264L4NkAm78zfnDzQJJvXuU3fMjRUvRxyPi5da"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "tests/keys/user.json"
