[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
m_ext = "29MecrtFgHzVJYUsSa7xgng1LA1eogpfgoNhHwxJvVr4"
scaled_ui_ext = "3C865D264L4NkAm78zfnDzQJJvXuU3fMjRUvRxyPi5da"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "tests/keys/user.json"

[scripts]
test = "yarn run jest --preset ts-jest tests/**/*.ts"
