[toolchain]
anchor_version = "0.31.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "2.1.0"     # Solana version to use(applies to all Solana tools)
package_manager = "yarn"     # JS package manager to use

[features]
seeds = false
skip-lint = false

[programs.localnet]
m_ext = "3C865D264L4NkAm78zfnDzQJJvXuU3fMjRUvRxyPi5da"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/keys/user.json"

[scripts]
test = "yarn run jest --preset ts-jest tests/**/*.ts"
