packages:
  - services/**/*
  - tests

catalog:
  '@types/bn.js': 5.2.0
  '@types/bs58': 4.0.1
  '@coral-xyz/anchor': 0.31.1
  '@m0-foundation/solana-m-sdk': 0.2.5
  '@solana-developers/helpers': 2.8.1
  '@solana/buffer-layout': 4.0.1
  '@solana/buffer-layout-utils': 0.2.0
  '@solana/spl-token': 0.4.13
  '@solana/web3.js': 1.98.2
  bn.js: 5.2.2
  fastestsmallesttextencoderdecoder: 1.0.22
  prettier: 2.6.2
  typescript: 5.8.3

onlyBuiltDependencies:
  - '@m0-foundation/solana-m-sdk'
  - bigint-buffer
  - bufferutil
  - utf-8-validate
